// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDemoUser = "demo_user"

// DemoUser mapped from table <demo_user>
type DemoUser struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name      string         `gorm:"column:name" json:"name"`
	Address   string         `gorm:"column:address" json:"address"`
	Age       int32          `gorm:"column:age" json:"age"`
}

// TableName DemoUser's table name
func (*DemoUser) TableName() string {
	return TableNameDemoUser
}
